/**
 * academies.js - アカデミー一覧データ
 *
 * 新しいアカデミーを追加するには、ACADEMIES配列にオブジェクトを追加してください。
 * 各オブジェクトには以下のプロパティが必要です:
 *   id, name, title, subtitle, color, icon, description, category, levels, modules, path
 */

const ACADEMIES = [
  {
    id: "boki",
    name: "boki-academy",
    title: "簿記3級アカデミー",
    subtitle: "日商簿記3級を図解で完全マスター",
    color: "#2563eb",
    icon: "📊",
    description: "仕訳、勘定科目、試算表、決算処理まで、日商簿記3級の全範囲を図解と演習で学びます。",
    category: "資格・試験",
    levels: 6,
    modules: 24,
    path: "../boki-academy/index.html"
  },
  {
    id: "comm",
    name: "comm-academy",
    title: "コミュニケーションアカデミー",
    subtitle: "人間関係を深めるコミュニケーション術",
    color: "#e85d04",
    icon: "🗣️",
    description: "初対面から深い人間関係を構築するコミュニケーション術を体系的に学びます。",
    category: "ビジネススキル",
    levels: 6,
    modules: 24,
    path: "../comm-academy/index.html"
  },
  {
    id: "intimacy",
    name: "intimacy-academy",
    title: "インティマシーアカデミー",
    subtitle: "親密な関係を築くスキルを学ぶ",
    color: "#be185d",
    icon: "💕",
    description: "親密な関係の構築と維持に必要な知識とスキルを学びます。",
    category: "ライフスキル",
    levels: 6,
    modules: 24,
    path: "../intimacy-academy/index.html"
  },
  {
    id: "eps",
    name: "eps-academy",
    title: "EPSアカデミー",
    subtitle: "EPSグループとCRO業界を徹底理解",
    color: "#1e40af",
    icon: "🏢",
    description: "EPSグループの全容とCRO業界の競合関係、クライアント構造を学びます。",
    category: "企業・業界研究",
    levels: 6,
    modules: 24,
    path: "../eps-academy/index.html"
  },
  {
    id: "pharma-sales",
    name: "pharma-sales-academy",
    title: "製薬営業アカデミー",
    subtitle: "製薬MRのための実践営業プロセス",
    color: "#0f766e",
    icon: "💊",
    description: "製薬MRのための実践的な営業プロセスを基礎から戦略まで体系的に学びます。",
    category: "営業・セールス",
    levels: 6,
    modules: 24,
    path: "../pharma-sales-academy/index.html"
  },
  {
    id: "sdtm",
    name: "sdtm-academy",
    title: "SDTMアカデミー",
    subtitle: "臨床データ標準化のプロを目指す",
    color: "#7c3aed",
    icon: "📋",
    description: "CDISC SDTMの基礎から実践まで、臨床データ標準化のプロフェッショナルを目指します。",
    category: "専門技術",
    levels: 6,
    modules: 24,
    path: "../sdtm-academy/index.html"
  },
  {
    id: "stat",
    name: "stat-academy",
    title: "統計検定2級アカデミー",
    subtitle: "統計検定2級を図解で完全攻略",
    color: "#059669",
    icon: "📈",
    description: "確率分布、推定・検定、回帰分析など統計検定2級の全範囲を図解で学びます。",
    category: "資格・試験",
    levels: 6,
    modules: 24,
    path: "../stat-academy/index.html"
  },
  {
    id: "pk",
    name: "pk-academy",
    title: "薬物動態アカデミー",
    subtitle: "ADME・PKパラメータを体系的に学ぶ",
    color: "#0891b2",
    icon: "🧪",
    description: "ADME（吸収・分布・代謝・排泄）の基礎からTDM、生物学的同等性試験、ポピュレーションPKまで体系的に学びます。",
    category: "専門技術",
    levels: 6,
    modules: 24,
    path: "../pk-academy/index.html"
  },
  {
    id: "framework",
    name: "framework-academy",
    title: "フレームワークアカデミー",
    subtitle: "世界のフレームワークを体系的にマスター",
    color: "#2563eb",
    icon: "🧩",
    description: "SWOT、ポーター、PDCA、デザインシンキングからリーンスタートアップまで、ビジネス・思考・コミュニケーション・マネジメントの全フレームワークを体系的に学びます。",
    category: "ビジネススキル",
    levels: 6,
    modules: 24,
    path: "../framework-academy/index.html"
  },
  {
    id: "smalltalk",
    name: "smalltalk-academy",
    title: "雑談アカデミー",
    subtitle: "雑談力を磨いて人間関係を豊かにする",
    color: "#f97316",
    icon: "☕",
    description: "「何を話せばいいかわからない」を解消！天気・ニュース・趣味から、場を和ませるテクニックまで雑談力を体系的に学びます。",
    category: "ライフスキル",
    levels: 6,
    modules: 24,
    path: "../smalltalk-academy/index.html"
  },
  {
    id: "nomikai",
    name: "nomikai-academy",
    title: "飲み会での会話アカデミー",
    subtitle: "飲み会を最高の時間にする会話術",
    color: "#d97706",
    icon: "🍺",
    description: "乾杯から二次会まで！飲み会のマナー・会話術・場の盛り上げ方・幹事力を完全マスターします。",
    category: "ライフスキル",
    levels: 6,
    modules: 24,
    path: "../nomikai-academy/index.html"
  },
  {
    id: "market-size",
    name: "market-size-academy",
    title: "市場規模アカデミー",
    subtitle: "日本の主要産業の市場規模とシェアを体系的に学ぶ",
    color: "#0d9488",
    icon: "📊",
    description: "自動車、IT、医薬品、金融、小売など日本の主要産業の市場規模と、各業界トップ企業の市場シェアを体系的に学びます。",
    category: "企業・業界研究",
    levels: 6,
    modules: 24,
    path: "../market-size-academy/index.html"
  },
  {
    id: "racehorse",
    name: "racehorse-academy",
    title: "競走馬の一生アカデミー",
    subtitle: "誕生から引退後まで、競走馬のライフサイクルを完全網羅",
    color: "#16a34a",
    icon: "🐴",
    description: "血統・配合から育成・調教、GIレース、健康管理、引退後のセカンドキャリアまで、競走馬の一生を体系的に学びます。",
    category: "ライフスキル",
    levels: 6,
    modules: 24,
    path: "../racehorse-academy/index.html"
  },
  {
    id: "sas-graph",
    name: "sas-graph-academy",
    title: "SASグラフアカデミー",
    subtitle: "100種類のSASグラフを完全マスター",
    color: "#2563eb",
    icon: "📉",
    description: "PROC SGPLOT、SGPANEL、GTLを使った100種類のグラフを、SASコード付きで体系的に学びます。臨床試験グラフも網羅。",
    category: "専門技術",
    levels: 6,
    modules: 24,
    path: "../sas-graph-academy/index.html"
  },
  {
    id: "ad-ops",
    name: "ad-ops-academy",
    title: "広告運用アカデミー",
    subtitle: "デジタル広告運用を基礎から戦略まで完全マスター",
    color: "#ea580c",
    icon: "📢",
    description: "Google Ads、Meta広告、YouTube広告からGA4分析まで、デジタル広告運用の全スキルを体系的に学びます。",
    category: "ビジネススキル",
    levels: 6,
    modules: 24,
    path: "../ad-ops-academy/index.html"
  },
  {
    id: "sns-ops",
    name: "sns-ops-academy",
    title: "SNS運用アカデミー",
    subtitle: "主要SNSの運用戦略を基礎から実践まで完全マスター",
    color: "#8b5cf6",
    icon: "📱",
    description: "X、Instagram、TikTok、YouTube、LINE、Facebookの運用戦略を、コンテンツ企画から分析・収益化まで体系的に学びます。",
    category: "ビジネススキル",
    levels: 6,
    modules: 24,
    path: "../sns-ops-academy/index.html"
  },
  {
    id: "creative",
    name: "creative-academy",
    title: "クリエイティブアカデミー",
    subtitle: "デザイン・コピー・動画制作を基礎から実践まで完全マスター",
    color: "#e11d48",
    icon: "🎨",
    description: "グラフィックデザイン、コピーライティング、動画制作、ブランディングまで、クリエイティブスキルの全領域を体系的に学びます。",
    category: "ビジネススキル",
    levels: 6,
    modules: 24,
    path: "../creative-academy/index.html"
  },
  {
    id: "mgmt-accounting",
    name: "mgmt-accounting-academy",
    title: "管理会計アカデミー",
    subtitle: "経営の意思決定を数字で武装する",
    color: "#0369a1",
    icon: "💰",
    description: "限界利益、損益分岐点、部門別採算、KPIツリー、NPV/IRR、ROIC経営まで、管理会計の全領域を図解で学びます。",
    category: "経営・財務",
    levels: 10,
    modules: 10,
    path: "../Desktop/管理会計アカデミー.md"
  },
  {
    id: "nanpa",
    name: "nanpa-academy",
    title: "ナンパアカデミー",
    subtitle: "声かけから始まるコミュニケーション戦略",
    color: "#e11d48",
    icon: "💬",
    description: "マインドセット、声かけの技術、会話術、連絡先交換、紳士の掟まで、初対面コミュニケーションの全スキルを学びます。",
    category: "ライフスキル",
    levels: 10,
    modules: 10,
    path: "../Desktop/ナンパアカデミー.md"
  },
  {
    id: "pharma-db",
    name: "pharma-db-academy",
    title: "商用データベース活用アカデミー",
    subtitle: "製薬業界特化：データで勝つ経営戦略",
    color: "#0f766e",
    icon: "🗄️",
    description: "IQVIA、MDV、JMDC、Cortellis、PubMed等、製薬業界の主要データベースの活用法を部門別に体系的に学びます。",
    category: "専門技術",
    levels: 10,
    modules: 10,
    path: "../Desktop/商用データベース活用アカデミー_製薬業界特化.md"
  },
  {
    id: "dumbbell",
    name: "dumbbell-academy",
    title: "ジムメニューアカデミー",
    subtitle: "ダンベルトレーニング完全攻略",
    color: "#b91c1c",
    icon: "🏋️",
    description: "胸・背中・肩・腕・脚・腹筋の全種目を図解付きで解説。週間プログラム、栄養管理、ケガ予防まで網羅します。",
    category: "ライフスキル",
    levels: 12,
    modules: 12,
    path: "../Desktop/ジムメニューアカデミー_ダンベルトレーニング.md"
  },
  {
    id: "social-structure",
    name: "social-structure-academy",
    title: "社会構造アカデミー",
    subtitle: "世の中の「見えないルール」を読み解く",
    color: "#6d28d9",
    icon: "🌐",
    description: "階層と格差、資本の4形態、権力構造、資本主義、ジェンダー、メディア、世界システムまで、社会の構造を多角的に学びます。",
    category: "教養・社会",
    levels: 12,
    modules: 12,
    path: "../Desktop/社会構造アカデミー.md"
  },
  {
    id: "facilitator",
    name: "facilitator-academy",
    title: "ファシリテーターアカデミー",
    subtitle: "会議を「成果が出る場」に変える技術",
    color: "#0284c7",
    icon: "🎯",
    description: "場のデザイン、引き出す技術、構造化、合意形成、オンラインファシリまで、ファシリテーションの全スキルを学びます。",
    category: "ビジネススキル",
    levels: 12,
    modules: 12,
    path: "../Desktop/ファシリテーターアカデミー.md"
  },
  {
    id: "ai-fundamentals",
    name: "ai-academy",
    title: "AIアカデミー",
    subtitle: "人工知能の本質を理解し、ビジネスに活かす",
    color: "#4f46e5",
    icon: "🤖",
    description: "機械学習、深層学習、LLM、プロンプトエンジニアリング、AIエージェント、倫理まで、AI技術の全体像を体系的に学びます。",
    category: "テクノロジー",
    levels: 11,
    modules: 11,
    path: "../Desktop/AIアカデミー.md"
  },
  {
    id: "ai-tools",
    name: "ai-tools-academy",
    title: "AI別特徴・活用例アカデミー",
    subtitle: "主要AIサービス完全ガイド 2026年版",
    color: "#7c3aed",
    icon: "🛠️",
    description: "ChatGPT、Claude、Gemini、Midjourney、Stable Diffusion等15以上のAIサービスを比較。料金、活用例、選定フローを網羅します。",
    category: "テクノロジー",
    levels: 12,
    modules: 15,
    path: "../Desktop/AI別特徴・活用例アカデミー.md"
  },
  {
    id: "company-setup",
    name: "company-setup-academy",
    title: "会社設立アカデミー",
    subtitle: "構想から登記、届出まで完全ガイド",
    color: "#15803d",
    icon: "🏛️",
    description: "株式会社vs合同会社の比較から、定款作成、登記、届出、法人口座開設、社会保険まで、会社設立の全ステップを学びます。",
    category: "起業・経営",
    levels: 15,
    modules: 15,
    path: "../Desktop/会社設立アカデミー.md"
  },
  {
    id: "subsidy",
    name: "subsidy-academy",
    title: "補助金アカデミー",
    subtitle: "中小企業・個人事業主のための完全攻略ガイド",
    color: "#ca8a04",
    icon: "💴",
    description: "ものづくり補助金、IT導入補助金、事業再構築補助金等の主要補助金を網羅。採択される事業計画書の書き方まで学びます。",
    category: "起業・経営",
    levels: 12,
    modules: 12,
    path: "../Desktop/補助金アカデミー.md"
  },
  {
    id: "bank-loan",
    name: "bank-loan-academy",
    title: "銀行融資アカデミー",
    subtitle: "中小企業・起業家のための完全ガイド",
    color: "#1d4ed8",
    icon: "🏦",
    description: "融資の種類、審査基準、格付け、決算書の見られ方、金利交渉、創業融資まで、銀行からお金を借りるための全知識を学びます。",
    category: "起業・経営",
    levels: 13,
    modules: 13,
    path: "../Desktop/銀行融資アカデミー.md"
  },
  {
    id: "sdrg",
    name: "sdrg-academy",
    title: "SDRGアカデミー",
    subtitle: "Study Data Reviewer's Guide 完全攻略",
    color: "#4338ca",
    icon: "📑",
    description: "SDRGの構成要素、各セクションの書き方、Pinnacle 21対応、Define.xmlとの関係、PMDA提出の留意点まで体系的に学びます。",
    category: "専門技術",
    levels: 12,
    modules: 12,
    path: "../Desktop/SDRGアカデミー.md"
  },
  {
    id: "adrg",
    name: "adrg-academy",
    title: "ADRGアカデミー",
    subtitle: "Analysis Data Reviewer's Guide 完全攻略",
    color: "#0e7490",
    icon: "📄",
    description: "ADRGの構成、ADaMデータセットの説明方法、導出ロジックの記載、SDTMからのトレーサビリティ、PMDA対応まで体系的に学びます。",
    category: "専門技術",
    levels: 12,
    modules: 12,
    path: "../Desktop/ADRGアカデミー.md"
  },
  {
    id: "sdtm-spec",
    name: "sdtm-spec-academy",
    title: "SDTM仕様書作成アカデミー",
    subtitle: "CRFからSDTMへのマッピング設計を極める",
    color: "#6d28d9",
    icon: "📝",
    description: "Annotated CRF、変数定義、マッピングロジック、SUPP、Controlled Terminology、Define.xml、Pinnacle 21対応まで網羅します。",
    category: "専門技術",
    levels: 12,
    modules: 12,
    path: "../Desktop/SDTM仕様書作成アカデミー.md"
  },
  {
    id: "sdtm-automation",
    name: "sdtm-automation-academy",
    title: "SDTM Automationアカデミー",
    subtitle: "メタデータ駆動型でSDTM変換を自動化する",
    color: "#0f172a",
    icon: "⚙️",
    description: "CDISC Library、ODM、Dataset-JSON、商用ツール、SAS/R/Python実装、CI/CD、End-to-Endワークフローまで体系的に学びます。",
    category: "専門技術",
    levels: 12,
    modules: 12,
    path: "../Desktop/SDTM_Automationアカデミー.md"
  },
  {
    id: "customer-analysis",
    name: "customer-analysis-academy",
    title: "顧客分析アカデミー",
    subtitle: "営業の「なぜ売れた」「なぜ失注した」を科学する",
    color: "#dc2626",
    icon: "🔍",
    description: "受注分析、失注原因調査、競合分析、LTV分析、離脱予兆分析、パイプライン分析まで、営業のデータドリブン化を体系的に学びます。",
    category: "営業・セールス",
    levels: 12,
    modules: 12,
    path: "../Desktop/顧客分析アカデミー.md"
  },
  {
    id: "osake",
    name: "osake-academy",
    title: "お酒の知識アカデミー",
    subtitle: "日本酒・ビール・ワイン・ウイスキー・焼酎・カクテルを体系的に学ぶ",
    color: "#b45309",
    icon: "🍶",
    description: "お酒の基礎知識から各ジャンルの深い知識、テイスティング、フードペアリング、マナーまで、お酒の世界を横断的に学べるプラットフォーム。",
    category: "ライフスキル",
    levels: 12,
    modules: 48,
    path: "../osake-academy/index.html"
  },
  {
    id: "neko",
    name: "neko-academy",
    title: "猫の育て方アカデミー",
    subtitle: "猫を迎える準備から健康管理・行動理解・しつけまで完全網羅",
    color: "#ea580c",
    icon: "🐱",
    description: "猫の飼育に必要な知識を初心者からベテランまで体系的に学べるプラットフォーム。食事・健康・行動・しつけ・多頭飼い・シニアケアまで網羅。",
    category: "ライフスキル",
    levels: 12,
    modules: 48,
    path: "../neko-academy/index.html"
  }
];

const CATEGORIES = ["すべて", "資格・試験", "ビジネススキル", "ライフスキル", "企業・業界研究", "営業・セールス", "専門技術", "経営・財務", "教養・社会", "テクノロジー", "起業・経営"];
